CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    ADDRESS VARCHAR
);

CREATE TABLE VEHICLES (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR UNIQUE,
    PRICE NUMBER (12,2),
    VENDOR_ID BIGINT NOT NULL,
    FOREIGN KEY (VENDOR_ID) references VENDORS(VENDOR_ID)
)