INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS) Values ('Jim', 'Parker', 'jparker@gmail.com', '07334321349', '123 Fakeville Avenue, Blundertown, G0T 3M');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS) Values ('Maisie', 'Andersen', 'mandersen@gmail.com', '07067243935', '321 Madeup Way, Sham City, F00L 3D');
INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS) Values ('Abdul', 'Majed', 'amajed@gmail.com', '07935385362', '42 Bogus Drive, Hoaxville, F4 K3D');

INSERT INTO VEHICLES (VEHICLE_MODEL, VEHICLE_BRAND, VEHICLE_MILEAGE, VEHICLE_PRICE, VEHICLE_IS_USED) Values ('RS3', 'Audi', 3000, 21000, 1);
INSERT INTO VEHICLES (VEHICLE_MODEL, VEHICLE_BRAND, VEHICLE_MILEAGE, VEHICLE_PRICE, VEHICLE_IS_USED) Values ('F-PACE', 'Jaguar', 3000, 21000, 1);
INSERT INTO VEHICLES (VEHICLE_MODEL, VEHICLE_BRAND, VEHICLE_MILEAGE, VEHICLE_PRICE, VEHICLE_IS_USED) Values ('MX-5', 'Mazda', 3000, 21000, 1);
INSERT INTO VEHICLES (VEHICLE_MODEL, VEHICLE_BRAND, VEHICLE_MILEAGE, VEHICLE_PRICE, VEHICLE_IS_USED) Values ('Prius', 'Toyota', 12000, 3000, 1);
INSERT INTO VEHICLES (VEHICLE_MODEL, VEHICLE_BRAND, VEHICLE_MILEAGE, VEHICLE_PRICE, VEHICLE_IS_USED) Values ('Type 01 1030PS', 'Jaguar', 0, 129000, 1);
