CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE_NUMBER VARCHAR,
    ADDRESS VARCHAR
);

CREATE TABLE VEHICLES (
    VEHICLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_MODEL VARCHAR,
    VEHICLE_PRICE INT,
    VEHICLE_MILEAGE INT,
    VEHICLE_BRAND VARCHAR,
    VEHICLE_IS_USED BOOLEAN
);